import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useState } from 'react'
import {
  fjumlahGanjilGenap,
  fkelompokGanjilGenap,
  fsamaAtauLebihDariSatu,
  fterbesar,
  fterkecil,
  furutkanNilai,
  jumlahBilanganAsli,
} from './utility'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [nilai, setNilai] = useState([])
  const [jumalhInput, setJumlahInput] = useState()
  const [terkecil, setTerkecil] = useState()
  const [terbesar, setTerbesar] = useState()
  const [samaAtauLebihDariSatu, setSamaAtauLebihDariSatu] = useState()
  const [urutan, setUrutan] = useState()
  const [jmlganjilGenap, setJmlGanjilGenap] = useState()
  const [ganjilGenap, setGanjilGenap] = useState()

  const inputNilai = (e) => {
    e.preventDefault()
    let temp = e.target[0].value.split(',')

    setJumlahInput(jumlahBilanganAsli(temp))
    setTerkecil(fterkecil(temp))
    setTerbesar(fterbesar(temp))
    setSamaAtauLebihDariSatu(fsamaAtauLebihDariSatu(temp).join(','))
    setUrutan(furutkanNilai(temp).join(','))
    setJmlGanjilGenap(fjumlahGanjilGenap(temp))
    console.log(jmlganjilGenap)
    setGanjilGenap(fkelompokGanjilGenap(temp))
    console.log(ganjilGenap)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='w-screen h-screen bg-blue-100 flex justify-center items-center p-3'>
        <div className='w-full h-full bg-white rounded-lg p-3'>
          <form onSubmit={inputNilai}>
            <label className='flex flex-col gap-2'>
              <span className='font-bold text-2xl capitalize'>
                input nilai pisah dengan koma, contoh: 11 22{' '}
              </span>
              <input
                type='text'
                className='bg-slate-300 rounded-full px-5 h-10'
              />
              <button
                type='submit'
                className='bg-blue-800 rounded-full py-2 font-bold text-white text-xl active:bg-blue-400'
              >
                Input
              </button>
            </label>
          </form>
          <div className='flex w-full flex-col gap-2'>
            <span className='font-bold text-black'>
              Jumalh Inputan / Variable Himpunan Bilangan Asli :
            </span>
            <span>{jumalhInput}</span>
            <span className='font-bold text-black'>
              Anggota terkecil dari Inputan / Variable Himpunan Bilangan Asli:
            </span>
            <span>{terkecil}</span>
            <span className='font-bold text-black'>
              Anggota terbesar dari Inputan / Variable Himpunan Bilangan Asli:
            </span>
            <span>{terbesar}</span>
            <span className='font-bold text-black'>
              anggota dari Inputan / Variable Himpunan Bilangan Asli dengan
              nilai angka sama dan lebih dari satu:
            </span>
            <span>{samaAtauLebihDariSatu}</span>
            <span className='font-bold text-black'>
              anggota yang memiliki nilai angka yang sama dan lebih dari satu
              diurutan:
            </span>
            <span>{urutan} </span>
            <span className='font-bold text-black'>
              Jumlah bilangan ganjil dan bilangan genap ada berapa jumlahnya
              masing-masing:
            </span>
            <span>
              ganjil {jmlganjilGenap.ganjil}, <br /> genap{' '}
              {jmlganjilGenap.genap}
            </span>
            <span className='font-bold text-black'>
              anggota himpunan bilangan asli dalam kelompok bilangan ganjil dan
              bilangan genap:
            </span>
            <span>
              ganjil {ganjilGenap.ganjil.join(',')}, <br /> genap{' '}
              {ganjilGenap.genap.join(',')}
            </span>
          </div>
        </div>
      </main>
    </>
  )
}
